### ISSUE TITLE
When initiating a session, it'll play for a few seconds then goes mute. 

### ISSUE THREAD

**Issue by beedo** [donkevlar/Bookshelf-Traveller#2]
I'm trying out the bot for the first time but whenever I start a book, it'll go for a few seconds then stop. The progress seems to continue based on Audiobookshelf despite no sound coming out of the bot.

**Comment by donkevlar** [comment]
By chance are you using an https connection. I've issues similar in nature using a connection like that. If you are, I'd suggest trying to use just an IP address instead or if you are hosting locally using the local host.

**Comment by donkevlar** [comment]
I know it's more of a workaround at the moment, but it's not an ffmpeg issue and more of a discord or maybe one of the synchronous processes happening in the back end. But know that I am actively looking into it 🙂

**Comment by donkevlar** [comment]
Just a quick update, turns out a recent discord update broke a large portion of voice bots on discord. The discord library that I use seems to be having similar issues. I also can't get it to even stream for a few seconds. If you are getting error 4020 on your logs, then its currently out of my hands until discord updates their API again.

**Comment by donkevlar** [comment]
Added hot fix, updating release to include hot fix. Big thanks to the interactions.py community for providing a hot fix for the discord api!

**Comment by donkevlar** [comment]
> I'm trying out the bot for the first time but whenever I start a book, it'll go for a few seconds then stop. The progress seems to continue based on Audiobookshelf despite no sound coming out of the bot.

Please make sure you are now using Beta V1.1.4 HOTFIX. This will show up in your logs when you first boot up the bot and will fix this issue.

**Comment by beedo** [comment]
Thanks, confirmed it's fixed now!
